###
POST  http://localhost:3500/items/upload-file
###
###
POST http://localhost:3500/items/new-folder
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNzYwNTc3My1jNmNmLTQ0NTgtYjExNy1hY2NmY2ZmOWUwN2YiLCJpYXQiOjE2OTA5NzU0MjUsImV4cCI6MTY5MDk3NjAyNX0.Rk4DlwKIjdmIN6GbyOhspM0mg6JakiuVxubRvqslipE
Content-Type: application/json

{
    "folderName" :"second-folder",
    "parentFolderId" : "6f16d232-bd98-4476-9a86-a670e9c7f3c4"
}
###
###
POST http://localhost:3500/items/share-item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNzYwNTc3My1jNmNmLTQ0NTgtYjExNy1hY2NmY2ZmOWUwN2YiLCJpYXQiOjE2OTA5NzU0MjUsImV4cCI6MTY5MDk3NjAyNX0.Rk4DlwKIjdmIN6GbyOhspM0mg6JakiuVxubRvqslipE
Content-Type: application/json

{
    "userMailId" : "donish@gmail",
    "itemId" : "4ab9f0a1-7c89-4c5b-aa31-9828ec321cc8",
    "permission" : {
        "value" : "3"
    }
}
###
###
POST http://localhost:3500/items/edit-item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMmNhOTQ4Yy0wMjRjLTRlNzItODkyMC1kMmFiMzk5ZmZiZmMiLCJpYXQiOjE2OTA5Njk4NjUsImV4cCI6MTY5MDk3MDQ2NX0.kgPEDpY7LsQQusUovG961TzKs_59IfrBDj3l9RtbykE
Content-Type: application/json

{
    "itemId" : "b7a400da-a517-4880-a8f1-4754689e4d14",
    "changingData" : {
        "newName" : "firstUpdatedFolder"
    }
}

###
###
GET  http://localhost:3500/items/download-file?itemId=16a44080-f1de-4792-9323-c543b356406e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMmNhOTQ4Yy0wMjRjLTRlNzItODkyMC1kMmFiMzk5ZmZiZmMiLCJpYXQiOjE2OTA5NzA3MDMsImV4cCI6MTY5MDk3MTMwM30.6J0kVUymvk3UP3tuDxP2Qbz5H_7lYPOVfRtK1SPyB-Q

###
###
POST http://localhost:3500/items/delete-file?fileId=ece22da3-35db-4f0b-afb1-24fc4514f03f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MTY1NjBiYi1iZmRkLTRjNjUtYjk0OC0zNzE2MzgxOGJjOTkiLCJpYXQiOjE2OTA5NzcxMTcsImV4cCI6MTY5MDk3NzcxN30.pyENXsvqbrecvEEVc3nbXVZDXl8b4MNgC9wmSDtQ_1k

###
###
//view item
GET http://localhost:3500/items/view-folder?itemId=223f79e5-3dd0-4ec0-8a2e-ff21258e7417
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MTY1NjBiYi1iZmRkLTRjNjUtYjk0OC0zNzE2MzgxOGJjOTkiLCJpYXQiOjE2OTEwMDExMTcsImV4cCI6MTY5MTAwMTcxN30.S11sARG4thYRXoWjt6PjnXl997kFBHBzZ2GfGySeUy8
###

###
GET http://localhost:3500/items/delete-folder?folderId=6f16d232-bd98-4476-9a86-a670e9c7f3c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNzYwNTc3My1jNmNmLTQ0NTgtYjExNy1hY2NmY2ZmOWUwN2YiLCJpYXQiOjE2OTA5NzY2NzEsImV4cCI6MTY5MDk3NzI3MX0.2GXzX_byyrO-Tf5fVIgt2WaDUpYtDAJT3VxUnpubydo

###
