###
POST  http://localhost:3500/files/upload

###
POST  http://localhost:3500/items/create-folder 
Content-Type: application/json

{
    "userId" : "b1e657f0-d298-4cf6-8598-16451c248805"
}
###
###
POST http://localhost:3500/items/new-folder 
Content-Type: application/json

{
    "userId" : "b1e657f0-d298-4cf6-8598-16451c248805",
    "foldername" :"second-folder"
}
###
###
POST http://localhost:3500/items/share-item
Content-Type: application/json

{
    "ownerId": "sibinbabu@gmail",
    "userMailId" : "sanjai@gmail",
    "itemId" : "eb9c16c9-b809-4521-b2dc-2b136b146735",
    "permissionValue" : {
        "p" : "1"
    }
}
###
###
POST http://localhost:3500/items/edit-item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMWU2NTdmMC1kMjk4LTRjZjYtODU5OC0xNjQ1MWMyNDg4MDUiLCJpYXQiOjE2OTAxOTg1OTcsImV4cCI6MTY5MDE5OTE5N30.WglRFwY_ptUuIHr-IKNNB5LapfaL-lZakp3VQNwjuSQ
Content-Type: application/json

{
    "userMailId" : "sanjai@gmail",
    "itemId" : "eb9c16c9-b809-4521-b2dc-2b136b146735"
}

###
###
POST http://localhost:3500/items/view-item
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMWU2NTdmMC1kMjk4LTRjZjYtODU5OC0xNjQ1MWMyNDg4MDUiLCJpYXQiOjE2OTAxOTg1OTcsImV4cCI6MTY5MDE5OTE5N30.WglRFwY_ptUuIHr-IKNNB5LapfaL-lZakp3VQNwjuSQ
Content-Type: application/json

{
    "userMailId" : "sanjai@gmail",
    "itemId" : "eb9c16c9-b809-4521-b2dc-2b136b146735"
}
