POST  http://localhost:3500/user/sign-up 
Content-Type: application/json

{
    "username" : "lijo",
    "email" : "Lijotvm@gmail",
    "password" : "lijotvm@123"
}
###
GET http://localhost:3500/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMWU2NTdmMC1kMjk4LTRjZjYtODU5OC0xNjQ1MWMyNDg4MDUiLCJpYXQiOjE2ODk5NDE2NDIsImV4cCI6MTY4OTk0MjI0Mn0.jCR4BPAKGc64s_wjsdspG_J77OFHJf6dzuMYqsnmip8
###
PUT  http://localhost:3500/user/update/64ae9d195a6e5d6b1043997e
Content-Type: application/json

{
    "name" : "sibin",
    "address" : "sibi@123"
}

###
POST http://localhost:3500/user/login/b1e657f0-d298-4cf6-8598-16451c248805
Content-Type: application/json

{
    "username" : "sibin",
    "password" : "sibi@123"
}