POST  http://localhost:3500/sign-up 
Content-Type: application/json

{
    "username" : "krishna",
    "address" : "krishna house",
    "phone_no" : "krish@gamil.com",
    "password" : "krish@123"
}
###
GET http://localhost:3500/64ae9a4eeec5aff728cd0a85
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFmYjlhZTBiMzMyMThhMDRiOTllODkiLCJpYXQiOjE2ODkyNDMxNjksImV4cCI6MTY4OTI0MzIyOX0.X9YsurS1Yhx5NMURdLTkaC2DOWuD8_5NSgqR7i0xWuU
###
GET http://localhost:3500/refresh/64ae88c55b070737a8ca965d

###
PUT  http://localhost:3500/update/64ae9d195a6e5d6b1043997e
Content-Type: application/json

{
    "name" : "rijin",
    "address" : "rijin@234"
}

###
POST http://localhost:3500/login/64afb9ae0b33218a04b99e89
Content-Type: application/json

{
    "username" : "krishna",
    "password" : "krish@123"
}